./configure \
--prefix=/usr/local/php-$phpversion \
--with-config-file-path=/usr/local/php-$phpversion/etc \
--enable-redis \
--with-mysql \
--with-mysqli \
--with-pdo-mysql \
--enable-fpm \
--with-curl \
--enable-memcache \
--enable-mongo \
--with-pcre-regex \
--with-zlib \
--with-gd \
--with-png-dir \
--with-jpeg-dir \
--with-vpx-dir \
--enable-gd-native-ttf \
--enable-gd-jis-conv \
--with-freetype-dir \
--with-bz2 \
--with-openssl \
--enable-bcmath \
--with-kerberos \
--enable-ftp \
--with-gettext \
--enable-opcache \
--enable-pcntl \
--enable-zip \
--with-pear \
--with-imagick \
--enable-mbstring \
--enable-exif

#--with-xpm-dir \
#--with-mcrypt \
